export const initialFormState = {
    id: "",
    name: "",
    picture: "",
    biography: "",
    birth_year: "",
    arrival_date: "",
    breed: "",
    gender: "",
    seen_by_vet: false,
    seen_by_farrier: false,
    service_horse: false,
    ex_race_horse: false,
    deceased: false,
    death_date: "",
    grooming_day: "",
    pasture: "",
    behavior_notes: "",
    regular_treatment: false,
    medical_notes: "",
    left_eye: "",
    right_eye: "",
    heart_murmur: false,
    cushings_positive: false,
    heaves: false,
    anhidrosis: false,
    shivers: false,
    bites: false,
    kicks: false,
    difficult_to_catch: false,
    problem_with_needles: false,
    problem_with_farrier: false,
    sedation_for_farrier: false,
    requires_extra_feed: false,
    requires_mash: false,
  };

export const breedItems = [
    { label: 'American Paint', value: 'American Paint' },
    { label: 'American Warmblood', value: 'American Warmblood' },
    { label: 'Anglo-Arabian', value: 'Anglo-Arabian' },
    { label: 'Appaloosa', value: 'Appaloosa' },
    { label: 'Appendix QH', value: 'Appendix QH' },
    { label: 'Arabian', value: 'Arabian' },
    { label: 'Arabian Cross', value: 'Arabian Cross' },
    { label: 'Belgian', value: 'Belgian' },
    { label: 'Donkey', value: 'Donkey' },
    { label: 'Draft Cross', value: 'Draft Cross' },
    { label: 'Grade', value: 'Grade' },
    { label: 'Haflinger', value: 'Haflinger' },
    { label: 'Mini Horse', value: 'Mini Horse' },
    { label: 'Morgan', value: 'Morgan' },
    { label: 'Mule', value: 'Mule' },
    { label: 'Mustang', value: 'Mustang' },
    { label: 'Paint', value: 'Paint' },
    { label: 'Quarter Horse', value: 'Quarter Horse' },
    { label: 'Standardbred', value: 'Standardbred' },
    { label: 'Tennessee Walker', value: 'Tennessee Walker' },
    { label: 'Thoroughbred', value: 'Thoroughbred' },
    { label: 'Warmblood Mix', value: 'Warmblood Mix' },
    { label: 'Welsh Pony', value: 'Welsh Pony' },
    { label: 'Other', value: 'Other' },
  ];